name: Anomalous Outbound Calls
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  unexpected-outbound-calls:
    name: AnomalousOutboundCalls
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
      - run: "curl https://pastebin.com -L  || true"
      - run: "curl https://google.com -L  || true"
      - run: "curl microsoft.com:443  --connect-timeout 5 || true"
      - run: "curl amazon.com:443  --connect-timeout 5 || true"
